- hosts: all
  become: yes
  roles:
    - role: config-golang
      go_version: '1.15'
    - clone-devstack-gate-to-workspace
    - role: create-devstack-local-conf
      enable_services: "{{ devstack_services | default(omit) }}"
    - role: install-devstack
      environment:
        OVERRIDE_ENABLED_SERVICES: "{{ devstack_override_enabled_services | default('') }}"
        PROJECTS: "{{ devstack_projects | default('') }}"
  tasks:
    - name: Run acceptance tests with gophercloud
      shell:
        cmd: |
          set -e
          set -o pipefail
          set -x
          echo $(export |grep OS_BRANCH)
          export ACCEPTANCE_TESTS="{{ acceptance_tests|default('') }}"
          go get ./... || true
          ./script/acceptancetest -v 2>&1 | tee $TEST_RESULTS_TXT
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ global_env }}'
