name: Pull Request backporting

on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  backporting:
    name: "Backporting"
    # Only react to merged PRs for security reasons.
    # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target.
    if: >
      github.event.pull_request.merged
      && (
        github.event.action == 'closed'
          && contains(github.event.pull_request.labels.*.name, 'backport-v1')
        || (
          github.event.action == 'labeled'
          && contains(github.event.label.name, 'backport-v1')
        )
      )
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token from the gophercloud-backport-bot github-app
        id: generate_token
        uses: getsentry/action-github-app-token@97c9e23528286821f97fba885c1b1123284b29cc
        with:
          app_id: ${{ secrets.BACKPORT_APP_ID }}
          private_key: ${{ secrets.BACKPORT_APP_PRIVATE_KEY }}

      - name: Backporting
        if: >
          contains(github.event.pull_request.labels.*.name, 'semver:patch')
          || contains(github.event.pull_request.labels.*.name, 'semver:minor')
          || contains(github.event.label.name, 'semver:patch')
          || contains(github.event.label.name, 'semver:minor')
        uses: kiegroup/git-backporting@4313be48e73b299a20b3c8290fd1ea8704e8dd5e
        with:
          target-branch: v1
          pull-request: ${{ github.event.pull_request.url }}
          auth: ${{ steps.generate_token.outputs.token }}
          no-squash: true
          strategy-option: find-renames

      - name: Report an error if backport unsupported labels
        if: >
          contains(github.event.pull_request.labels.*.name, 'semver:major')
          || contains(github.event.pull_request.labels.*.name, 'semver:unknown')
          || contains(github.event.label.name, 'semver:major')
          || contains(github.event.label.name, 'semver:unknown')
        uses: thollander/actions-comment-pull-request@1d3973dc4b8e1399c0620d3f2b1aa5e795465308
        with:
          message: |
            Labels `semver-major` or `semver-unknown` can not trigger backports.
            The PR has to be labeled `semver-patch` or `semver-minor`.
